pipeline {
    agent {
        dockerfile {
            filename 'Dockerfile'
            dir 'm4/demo1/1.1'
        }
          
          }
    
    stages {
        stage('Verify') {
            steps {
                sh '''
                  dotnet --list-sdks
                  dotnet --list-runtimes
                '''
                sh 'printenv'
                sh 'ls -l "$WORKSPACE"'
            }
        }
        stage('Build') {
            steps {
                echo 'dotnet build "$WORKSPACE/m4/src/Pi.Web/Pi.Web.csproj"'
            }
        }
        stage('Unit Test') {
            steps {
              dir("$WORKSPACE/m4/src") {
                sh '''
                    node --version
                    svn --version
                '''
              }
            }
        }
        stage('Smoke Test') {
            steps {
              echo 'dotnet "$WORKSPACE/m4/src/Pi.Web/bin/Debug/netcoreapp3.1/Pi.Web.dll"'
            }
        }
    }
}
